### ISSUE TITLE
Set WETH address of Optimism

### ISSUE THREAD

**Issue by mizdler** [wormhole-foundation/wormhole#3725] opened 2024-01-21 22:39 UTC
Similar to #2796
WETH address of Optimism is unset.
I believe this is the canonical WETH of Optimism:  [`0x4200000000000000000000000000000000000006`](https://optimistic.etherscan.io/token/0x4200000000000000000000000000000000000006)

**Comment by evan-gray** [comment] 2024-01-22 14:53
Confirmed that WETH is currently `0x0000000000000000000000000000000000000000` on the [Token Bridge on Optimism](https://optimistic.etherscan.io/address/0x1d68124e65fafc907325e3edbf8c4d84499daa8b#readProxyContract) and concur with setting it to `0x4200000000000000000000000000000000000006` just like the [Token Bridge on Base](https://basescan.org/address/0x8d2de8d2f73F1F4cAB472AC9A881C9b123C79627#readProxyContract)

**Comment by evan-gray** [comment] 2024-01-31 00:57
Closing as it looks like this governance was performed and the Optimism token bridge was upgraded this morning

**Closed by evan-gray** 2024-01-31 00:57 UTC
Labels: bug
