### ISSUE TITLE
ci: Tilt tests make invalid API requests

### ISSUE THREAD

**Issue by tbjump** [wormhole-foundation/wormhole#3098] opened 2023-06-15 15:03 UTC
Some test seems to be requesting VAAs from the Guardian without specifying the sequence number, resulting in logs like this:

`2023-06-15T14:19:24.6313990Z      guardian │ 2023-06-15T14:19:24.628Z	INFO	guardian-0	finished unary call with code NotFound	{"_privateLogEntry": true, "grpc.start_time": "2023-06-15T14:19:24Z", "system": "grpc", "span.kind": "server", "grpc.service": "publicrpc.v1.PublicRPCService", "grpc.method": "GetSignedVAA", "grpc.requestbody": {"msg": {"messageId":{"emitterChain":"CHAIN_ID_BSC","emitterAddress":"0000000000000000000000000290fb167208af455bb137780163b7b7a9a10c16"}}}, "x-forwarded-for": [], "peer.address": "172.17.0.19:48578", "error": "rpc error: code = NotFound desc = requested VAA not found in store", "grpc.code": "NotFound", "grpc.time_ms": 0.19}
`

This also happens on runs that are overall, e.g. https://github.com/wormhole-foundation/wormhole/actions/runs/5279905814/jobs/9551269230?pr=3097. 

In the successful run there were 142 instances of this error, therefore it seems to be a bug rather than an intentional test.

**Comment by bruce-riley** [comment] 2024-04-18 15:50
This is really not a bug in the tests. These are actually cases where the sequence number is zero. A sequence number is zero gets omitted by the marshal function. 

Closing this issue.

**Closed as completed by bruce-riley** 2024-04-18 15:50 UTC
Labels: bug
