### ISSUE TITLE
sui: lower `signAndExecuteTransactionBlock` RPC processing latency

### ISSUE THREAD

**Issue by a5-pickle** [wormhole-foundation/wormhole#2670] opened 2023-04-18 00:03 UTC
## Description and context
While interacting with the public testnet RPC, we have encountered 504 (timeout) errors, but only using the Typescript SDK. Somehow when we use the `sui` CLI tool (specifically the `client` command) to execute, we get a successful transaction. **NOTE: This behavior does not occur when we interact with a local validator.**

We want to explore using [WaitForEffectsCert] when executing `signAndExecuteTransactionBlock`, where we would have to poll using `getTransaction` until we receive a valid transaction. This may help alleviate the timeout issue.

## Definition of done
At least in `worm` CLI, modify all Sui transaction execution using `signAndExecuteTransactionBlock` to use the above option and add polling. Test this change by trying to execute the `init-wormhole` command successfully.

[waitforeffectscert]: https://github.com/MystenLabs/sui/blob/ee8a72527084f8e8196631654711fae739ee1307/sdk/typescript/src/signers/signer-with-provider.ts#L127

**Comment by AlberErre** [comment] 2023-04-18 08:59
Hey @a5-pickle I've been taking a look at this issue here -> https://github.com/wormhole-foundation/wormhole/tree/sui/sdk-transfer/clients/js/sui and I would love to give it a try 🏄‍♂️

could you assign me this issue? 👀

**Comment by aadam-10** [comment] 2023-04-18 15:09
hi @AlberErre, feel free to take a shot at this, and thanks in advance! be sure to target the `sui/integration_v2` branch with the PR as that's where we're currently funneling all Sui work while it's ongoing.

**Comment by AlberErre** [comment] 2023-04-19 20:16
hey @a5-pickle @aadam-10! - I have implemented the `polling` method, as well as updating the `signAndExecuteTransactionBlock` to use `WaitForEffectsCert` requestType with this new polling 🎉  

Here is the PR -> https://github.com/wormhole-foundation/wormhole/pull/2747

Although, I would like to reproduce your 504 error on my side to verify everything 👀 

@a5-pickle could you please pass me the `testnet RPC` address you're using? as well the args you've passed to `worm sui init-wormhole` command `(network, package-id, initial-guardian)`? 🙏🏼  Thanks!

**Comment by a5-pickle** [comment] 2023-04-20 14:18
> hey @a5-pickle @aadam-10! - I have implemented the `polling` method, as well as updating the `signAndExecuteTransactionBlock` to use `WaitForEffectsCert` requestType with this new polling 🎉
> 
> Here is the PR -> #2747
> 
> Although, I would like to reproduce your 504 error on my side to verify everything 👀
> 
> @a5-pickle could you please pass me the `testnet RPC` address you're using? as well the args you've passed to `worm sui init-wormhole` command `(network, package-id, initial-guardian)`? 🙏🏼 Thanks!

Hello! Very nice, I'm glad you picked this task up. We really appreciate it :)

### Testnet RPC
We use is just the public full node: https://fullnode.testnet.sui.io:443.

### Execution
To get to the point of calling `init-wormhole`, first try publishing the package via `worm sui deploy`:
```shell
worm sui deploy wormhole -n testnet -k $YOUR_KEY -r https://fullnode.testnet.sui.io:443
```
where `YOUR_KEY` is a private key resembling one of the lines found in your _sui.keystore_ file (or you can generate another private key using the `sui` CLI). **You will need testnet SUI to pay for gas. If you have trouble accessing the faucet, let me know and I can send you some.**

The above command publishes the package to Sui testnet. The output will give you a package ID that you will need to reference for `init-wormhole`:
```shell
worm sui init-wormhole -n testnet -k $YOUR_KEY -i deadbeefdeadbeefdeadbeefdeadbeefdeadbeef -p $PACKAGE_ID -r https://fullnode.testnet.sui.io:443
```
If this succeeds, you should see a bunch of IDs in the output including Wormhole State ID.

Feel free to link the transaction from https://explorer.sui.io/ if it does succeed.

**NOTE: I've been adding the `-r` argument because I think the testnet network is misconfigured to the devnet RPC. If you add a fix to this, too, then we won't have to pass this into your commands.**

Thank you again. I hope your fix results in a successful testnet transaction!

**Comment by AlberErre** [comment] 2023-04-20 22:30
Thank you for such a complete description @a5-pickle 🎉 ! - I'm very glad you found the time to write it down 🙏🏻

I'm having an issue with `testnet` tokens, I was able to register on discord and get `2 sui tokens` on testnet. 
However, I think it's not enough tokens.

While trying to run `worm sui deploy` command, I'm facing the following error:
```
Error: Dry run failed, could not automatically determine a budget: InsufficientGas
```
Could you send me a bit more? 👀  my [testnet address](https://explorer.sui.io/address/0x063db16b1d044897b193bac9b9acd80ae42b01021e78548bfc67e0fa084bfa81?network=testnet) is the following:
````
0x063db16b1d044897b193bac9b9acd80ae42b01021e78548bfc67e0fa084bfa81
````

Thanks!

**Comment by AlberErre** [comment] 2023-04-20 22:47
Also, I think I noticed a bug on `clients/js/sui/publish.ts` 🐞

While using `getAllLocalPackageDependencyPaths` method, it tries to access a missing file on runtime.

The reason is that `fs.renameSync(defaultTomlPath, tempTomlPath) (line 201)` method deletes the original file (**Move.toml**), and generates a temp file (**Move.temp.toml**) until the process finishes.

I just commited a fix in this same branch updating `getAllLocalPackageDependencyPaths` param to fix it ✅ -> https://github.com/wormhole-foundation/wormhole/pull/2747/commits/21114983da081f9affe8390dcdc08199ee242694

**Comment by gator-boi** [comment] 2023-04-21 14:55
@AlberErre I have sent you 5 testnet sui tokens.

**Comment by AlberErre** [comment] 2023-04-21 23:14
@a5-pickle @aadam-10 @gator-boi 

Woah! what a ride 🎢

I finally deployed the sui package, and was able to reproduce the `504` error. 

After that, 🕵️‍♂️ I went deep and detected that main issue comes from the following http `POST` method: 
````
{
  method: 'POST',
  body: '{"method":"suix_getOwnedObjects","jsonrpc":"2.0","params":["0x063db16b1d044897b193bac9b9acd80ae42b01021e78548bfc67e0fa084bfa81",{"filter":{"StructType":"0xee407524b519235f2ebb523ee6032346c3030d6a9588d0863ac4623d5e8f2624::setup::DeployerCap"},"options":{"showContent":true}},null,null],"id":"ce994cfa-e8bd-40cf-9959-46162e2dd2f9"}',
  headers: {
    'Content-Type': 'application/json',
    'Client-Sdk-Type': 'typescript',
    'Client-Sdk-Version': '0.32.1',
    'Client-Target-Api-Version': '0.29.0'
  }
}
````

Basically, the `filter` is taking too long to execute.
This triggers a timeout on the RPC server, which throws a `504` error 🚨

Surprisingly, I tried to execute this `suix_getOwnedObjects` API method without this `filter`, and it responds very fast 🏇💨

**Why does it work so fast without a filter?** 🤨 because every response is capped by using pagination 📚

As a result, I implemented a `findOwnedObjectByType` function to directly download all OwnedObjects and navigate them until finding our target type. This uses`cursor` to search in every page. You can check the API docs [here](https://docs.sui.io/sui-jsonrpc#suix_getOwnedObjects).

You can take a look at this implementation here ✅ -> https://github.com/wormhole-foundation/wormhole/pull/2747/commits/6ce00b11e62aa5a30c8575bd80a9acef20d476af

This solution is not 100% optimal, as at the worst case, we will navigate all the OwnedObjects to finally return a `null`.
However, this ensures no `504` error is triggered.

I would like to know what you think about this 👀

Finally, I applied a rollback on `WaitForEffectsCert` and polling changes, as they were not successful while testing it. They weren't able to fix the `504`, and also returned a very confusing `RPC code: -32000` errors while executing calls.

I've updated the PR accordingly 🎉

**Comment by AlberErre** [comment] 2023-04-21 23:21
@a5-pickle 

Also, here is the successful transaction for the `worm sui init-wormhole` command 🎉 -> https://explorer.sui.io/txblock/AhTsGSvqStem9mhomevWSfrXSxh7VHjAQy5JJKqsBiHa?network=testnet

**Comment by a5-pickle** [comment] 2023-04-23 12:32
@AlberErre great sleuthing! I'm sorry that I misattributed the 504 error to begin with. Really glad you found the culprit.

Regarding the underlying issue, it might be nice to create an issue on Mysten's Sui repo (but only if you have the bandwidth). As far as what we want to accomplish, this PR does everything we had hoped.

Thank you for all the time you put into this. I'll have a chance to review your PR sometime tomorrow. Very excited to get this merged in!

**Comment by AlberErre** [comment] 2023-04-24 18:14
Thank you @a5-pickle ! 🚀 I've enjoyed this issue very much 👀

I've cleaned up both code and PR description because of these last changes 🧹

Here is the updated PR -> https://github.com/wormhole-foundation/wormhole/pull/2747

Also, I've created an [issue](https://github.com/MystenLabs/sui/issues/11231) on Mysten's Sui repo reporting this problem 👍

**Comment by aadam-10** [comment] 2023-04-24 20:12
thanks @AlberErre for everything so far. according to Mysten Labs, this is fixed in https://github.com/MystenLabs/sui/pull/11200 and rollout will start soon. I can keep an eye out and let you know when it's rolled out in case you want to test.

**Comment by AlberErre** [comment] 2023-04-25 15:50
Great! @aadam-10, this would be ideal as it will solve the main issue directly 🎉

I have updated the PR accordingly  👍, I've reused the original implementation, but surrounding it with a `try-catch` block.

In case the `filter` works correctly, it would behave as usual. Although, if another regression happens in the future, by returning a `504 Gateway Time-out` error again, it will be handled by `findOwnedObjectByType` method.

**Comment by AlberErre** [comment] 2023-04-27 18:08
@a5-pickle we can resolve this issue, as #2747 has been merged 🎉

**Closed** 2023-05-02 14:26 UTC
Labels: sui

**Comment by aadam-10** [comment] 2023-05-10 15:06
sry to ping you here @AlberErre - I tried to reach out to you on your gmail and twitter regarding wormhole grants but they may have missed you or the spam filters ate them. do you have a preferred method of comms where we can have a word?

**Comment by AlberErre** [comment] 2023-05-10 16:12
Just replied back @aadam-10 🎉
